apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prometheus-monitorable-namespace-roles-template
  labels:
    app: prometheus
  annotations:
    openshift.io/display-name: "Red Hat Fuse prometheus-operator install"
    openshift.io/provider-display-name: "Red Hat, Inc."
    tags: "prometheus,prometheus-operator,monitoring"
    iconClass: "icon-rh-integration"
    version: "1.0"
parameters:
  - name: PROMETHEUS_NAMESPACE
    displayName: Prometheus Namespace
    value: fuse-infra
    required: true
    description: Namespace in which the prometheus-operator is installed.
  - name: MONITORABLE_NAMESPACE
    displayName: Monitorable Namespace
    value: fuse-app
    required: true
    description: Namespace to be monitored by Prometheus

objects:

# Prometheus Operator Role
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-operator
    namespace: ${MONITORABLE_NAMESPACE}
  rules:
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - '*'
    - apiGroups:
        - monitoring.coreos.com
      resources:
        - alertmanagers
        - prometheuses
        - prometheuses/finalizers
        - alertmanagers/finalizers
        - servicemonitors
        - prometheusrules
      verbs:
        - '*'
    - apiGroups:
        - apps
      resources:
        - statefulsets
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - configmaps
        - secrets
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - list
        - delete
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
      verbs:
        - get
        - create
        - update
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - namespaces
      verbs:
        - get
        - list
        - watch

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-operator
    namespace: ${MONITORABLE_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-operator
  subjects:
    - kind: ServiceAccount
      name: prometheus-operator
      namespace: ${PROMETHEUS_NAMESPACE}

# Prometheus Role
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: ${MONITORABLE_NAMESPACE}
    name: prometheus
  rules:
    - apiGroups: [""]
      resources:
        - nodes
        - nodes/proxy
        - services
        - endpoints
        - pods
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources:
        - configmaps
      verbs: ["get"]

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: prometheus
    namespace: ${MONITORABLE_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus
  subjects:
    - kind: ServiceAccount
      name: prometheus
      namespace: ${PROMETHEUS_NAMESPACE}