apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prometheus-service-monitor
  labels:
    app: prometheus-service-monitor
  annotations:
    openshift.io/display-name: "Red Hat  service-monitor install"
    openshift.io/provider-display-name: "Red Hat, Inc."
    description: "A ServiceMonitor specifies how groups of services should be monitored - this template defines how to monitor an application for Prometheus."
    tags: "fuse,prometheus,prometheus-operator,monitoring"
    iconClass: "icon-rh-integration"
    version: "1.0"

parameters:
  - name: SERVICE_NAMESPACE
    displayName: Namespace
    value: fuse
    required: true
    description: Namespace of the
  - name: SERVICE_NAME
    displayName: Service Name
    value: 'myservicename'
    required: true
    description: The service name of the application to monitor.
  - name: SERVICE_TEAM
    displayName: Fuse Service Team
    value: 'fuse'
    required: true
  - name: ENDPOINT_PORT
    displayName: Endpoint port
    value: 'web'
    required: true
  - name: APP_LABEL
    value: 'web'
    required: true


objects:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: ${SERVICE_NAME}-servicemonitor
      labels:
        team: ${SERVICE_TEAM}
        app: prometheus
    spec:
      selector:
        matchLabels:
          app: ${APP_LABEL}
      namespaceSelector:
        matchNames:
          - ${SERVICE_NAMESPACE}
      endpoints:
        - port: ${ENDPOINT_PORT}
