apiVersion: v1
kind: Template
metadata:
  name: amq-prometheus-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: 'Service for the prometheus node exporter on broker pod 1'
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD1_NAME}-prometheus-service
  spec:
    ports:
      - name: prometheus
        port: 9779
        protocol: TCP
        targetPort: 9779
    selector:
      statefulset.kubernetes.io/pod-name: ${POD1_NAME}
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: 'Service for the prometheus node exporter on broker pod 2'
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD2_NAME}-prometheus-service
  spec:
    ports:
      - name: prometheus
        port: 9779
        protocol: TCP
        targetPort: 9779
    selector:
      statefulset.kubernetes.io/pod-name: ${POD2_NAME}
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: 'Service for the prometheus node exporter on broker pod 3'
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD3_NAME}-prometheus-service
  spec:
    ports:
      - name: prometheus
        port: 9779
        protocol: TCP
        targetPort: 9779
    selector:
      statefulset.kubernetes.io/pod-name: ${POD3_NAME}
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD1_NAME}-prometheus
  spec:
    port:
      targetPort: prometheus
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${POD1_NAME}-prometheus-service
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD2_NAME}-prometheus
  spec:
    port:
      targetPort: prometheus
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${POD2_NAME}-prometheus-service
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${POD3_NAME}-prometheus
  spec:
    port:
      targetPort: prometheus
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${POD3_NAME}-prometheus-service
      weight: 100
    wildcardPolicy: None

parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: Name of the application label that should be used in all resources.
    required: true
  - name: POD1_NAME
    displayName: Name of first broker pod
    description: Name of first broker pod.
    required: true
  - name: POD2_NAME
    displayName: Name of second broker pod
    description: Name of second broker pod.
    required: true
  - name: POD3_NAME
    displayName: Name of third broker pod
    description: Name of third broker pod.
    required: true